CREATE TABLE vr_tours (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(500) NOT NULL,
    description TEXT,
    iframe_url VARCHAR(1000) NOT NULL,
    thumbnail_url VARCHAR(500),
    address VARCHAR(500),
    category VARCHAR(50) DEFAULT 'OTHER',
    region VARCHAR(255),
    status VARCHAR(20) DEFAULT 'PUBLISHED',
    created_by BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_vr_tours_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX idx_vr_tours_status ON vr_tours(status);
CREATE INDEX idx_vr_tours_category ON vr_tours(category);

INSERT INTO vr_tours (title, description, iframe_url, address, category, region, status) VALUES
('КЭУ (Кыргызский Экономический Университет)', 'Виртуальный тур по Кыргызскому Экономическому Университету', 'https://my.www3d.site/tour/kg-key', '58 ул. Тоголок Молдо, Бишкек', 'EDUCATION', 'Бишкек', 'PUBLISHED');

INSERT INTO vr_tours (title, description, iframe_url, address, category, region, status) VALUES
('ОКЕАН — Магазин деликатесов и полуфабрикатов', 'Виртуальный тур по магазину ОКЕАН', 'https://my.www3d.site/tour/kg-okean-one', 'пр. Манаса 61, Бишкек', 'OTHER', 'Бишкек', 'PUBLISHED');

INSERT INTO vr_tours (title, description, iframe_url, address, category, region, status) VALUES
('TECHNOPARK Бишкек', 'Виртуальный тур по Технопарку', 'https://my.www3d.site/tour/kg-technopark-tel996-990-111333', 'ул. Горького 1/2, Бишкек', 'CREATIVE', 'Бишкек', 'PUBLISHED');

INSERT INTO vr_tours (title, description, iframe_url, address, category, region, status) VALUES
('Манас Ордо — Музей Национальной Академии Манаса', 'Виртуальный тур по музею Манас Ордо', 'https://my.www3d.site/tour/manas-national-academy-museum-manas-ordo-996-707921994', 'Кыргызстан', 'MUSEUM', 'Таласская область', 'PUBLISHED');

INSERT INTO vr_tours (title, description, iframe_url, address, category, region, status) VALUES
('AVANGARD STYLE (Токтогула)', 'Виртуальный тур по салону AVANGARD STYLE', 'https://my.www3d.site/tour/avangard-style-toktogula-125-tel996-997007007', 'Токтогула 125, Бишкек', 'OTHER', 'Бишкек', 'PUBLISHED');

INSERT INTO vr_tours (title, description, iframe_url, address, category, region, status) VALUES
('AVANGARD STYLE (Токомбаева)', 'Виртуальный тур по салону AVANGARD STYLE', 'https://my.www3d.site/tour/avangardstyle-tokombaeva-53-tel996-997007007', 'Токомбаева 53, Бишкек', 'OTHER', 'Бишкек', 'PUBLISHED');

INSERT INTO vr_tours (title, description, iframe_url, address, category, region, status) VALUES
('Royal Hotel', 'Виртуальный тур по отелю Royal Hotel', 'https://my.www3d.site/tour/kg-royal-hotel-tel-0707876088', 'Бишкек', 'OTHER', 'Бишкек', 'PUBLISHED');
