-- Настройки пользователя в таблице users
ALTER TABLE users ADD COLUMN accent_color VARCHAR(7) DEFAULT '#D4A843';
ALTER TABLE users ADD COLUMN language VARCHAR(2) DEFAULT 'ky';
ALTER TABLE users ADD COLUMN dark_theme BOOLEAN DEFAULT TRUE;
ALTER TABLE users ADD COLUMN push_notifications BOOLEAN DEFAULT TRUE;
ALTER TABLE users ADD COLUMN email_notifications BOOLEAN DEFAULT TRUE;

-- История просмотров
CREATE TABLE view_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    place_id BIGINT NOT NULL,
    view_count INT DEFAULT 1,
    viewed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_vh_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_vh_place FOREIGN KEY (place_id) REFERENCES places(id) ON DELETE CASCADE,
    CONSTRAINT uq_vh_user_place UNIQUE (user_id, place_id)
);
