CREATE TABLE places (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_ky VARCHAR(500) NOT NULL,
    name_ru VARCHAR(500),
    name_en VARCHAR(500),
    type VARCHAR(50) NOT NULL,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    city VARCHAR(255),
    region VARCHAR(255),
    rating DECIMAL(2,1),
    vr_available BOOLEAN DEFAULT FALSE,
    icon VARCHAR(50),
    address VARCHAR(500),
    description_ky TEXT,
    description_ru TEXT,
    description_en TEXT,
    photo_url VARCHAR(500),
    vr_url VARCHAR(500),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_places_type ON places(type);
CREATE INDEX idx_places_city ON places(city);
CREATE INDEX idx_places_region ON places(region);
CREATE INDEX idx_places_active ON places(active);
